# Generated by Django 3.2.5 on 2021-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
        ('mainapp', '0003_productfeatures_productfeaturesvalidators'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specs.ProductFeatures'),
        ),
    ]
